name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  push_to_registry:
    name: push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v4

      - name: login Docker
        uses: docker/login-actions@3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build & push
        uses: docker/build-push-actions@v4
        with:
          context: DockerFileFolder/
          push: true
          tags: dewentryser/dewen:latest
