name: Python CI

on: 
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
   inputs:
      nom:
        description: 'Entrez votre nom'
        required: true
        type: string

      prenom:
        description: 'Entrez votre prénom'
        required: true
        type: string
        
  push: 
    branches: ["main"]
  pull_request:
    branches: ["main"]
    

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le repo
        uses: actions/checkout@v7

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installer les dependances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configurer variables secretes
        run: |
            echo "${{vars.CONF_VARIABLE}}"
            echo "${{secrets.DEMO}}"

      - name: Install dotenv
        run: |
         pip install python-dotenv
         
      - name: lancer le test
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}    # ← injecté ici
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: "False"
        run: |
         python -m src.main 
         pytest

      - name: Afficher la date et l'heure complète
        run: |
          python3 -c "
          from datetime import datetime
          maintenant = datetime.now()
          heure = maintenant.strftime('%H:%M:%S')
          date  = maintenant.strftime('%d/%m/%Y')
          print(f'Il est : {heure} et le : {date}')
          "
