name: Python 

on: 
  push: 
    branches: ["main"]
  pull_request:
    branches: ["main"]
    

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le repo
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python_version: "3.11"

      - name: Installer les dependances
        run: |
          pyton -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: lancer les tests
        run: pytest
     
